language: elm
elm-test: 0.19.0-rev6
before_install: npm install parcel-bundler
script:
- npm test
- parcel build src/index.html --public-url ./
deploy:
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: LMkEtn37/2chkf8pu1brT4cveAzqIAt0tH5jqZhTsu6D7IVq3ZuA8TolRhEoSRsRk6Mwhw0KLxrdDhvThhZSvB3HDWdWr3IQRwKfzq2B0qMMct4qXvJNNFI9ZtwW5HcH+Ur6iXOPC2ivTzW0K9tyasoxuocdVPp2j4sKnNkulUMcm3X7wH4wGuyNNxGxvrq4AS4XA9A9IzxtSBZhNWzwJWBBLJjqjAwpSExa0DjELqBfe1G6ifCoQt1MxgDwsihHa8pwBFFoK8uNX8xW6VZ+w41BiVVUoAHExv9a2Tgp2mT/9HAzTEEN5M2ef73x1aVTddhTgWHdvgPUjYkPZ2dVfmjVbVXth3Buj668iTpW8JDdce+MB7Zu7tLYp+Ka1I6SOzvnQ0mh8YyjPWyxwS5Rxuo4KxCAoUc9zfUZKTWE/86sMMozvAyJiFQDQGjrH2iGgjd+14PkwbSdKqn272tZE1rVuAoxe4GGu9uCnO8BGyXSLjmo7fkmKQDj/cZ4K8CrscELy5CF46DgT1kpJ3e4KtvQao42p26YtucHbYYsdWaxpce3YUYbNNR4vQ1wN5vH8mrz2/0yvvfFNrcrfOqcnXS56uAUIDPA/EhbmWEkeS3ANLh0r/bTU5QVJdaZT3LfLSPdVrgv74Wkg1be5uWOXkcSfU/R6U1fhBHcy36+3yE=
